// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func hello(name string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Cat Facts</title><script src=\"https://cdnjs.cloudflare.com/ajax/libs/htmx/1.9.10/htmx.min.js\"></script><style>\n                .container {\n                    max-width: 600px;\n                    margin: 50px auto;\n                    padding: 20px;\n                    text-align: center;\n                    font-family: Arial, sans-serif;\n                }\n                button {\n                    padding: 10px 20px;\n                    font-size: 16px;\n                    cursor: pointer;\n                    background-color: #4caf50;\n                    color: white;\n                    border: none;\n                    border-radius: 4px;\n                }\n                #fact-display {\n                    margin-top: 20px;\n                    padding: 15px;\n                    border: 1px solid #ddd;\n                    border-radius: 4px;\n                    min-height: 50px;\n                }\n            </style><script src=\"/main.js\"></script></head><body><div class=\"container\"><h1>Random Cat Facts</h1><button hx-get=\"https://catfact.ninja/fact\" hx-trigger=\"click\" hx-target=\"#fact-display\" hx-swap=\"innerHTML\">Get New Cat Fact</button><div id=\"fact-display\">Click the button to get a cat fact!</div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
